CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_connections` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `provider` VARCHAR(30) NOT NULL,
    `site_url` VARCHAR(500) DEFAULT NULL,
    `property_id` VARCHAR(191) DEFAULT NULL,
    `client_id` VARCHAR(500) DEFAULT NULL,
    `client_secret_envelope` LONGTEXT DEFAULT NULL,
    `access_token_envelope` LONGTEXT DEFAULT NULL,
    `refresh_token_envelope` LONGTEXT DEFAULT NULL,
    `api_key_envelope` LONGTEXT DEFAULT NULL,
    `token_expires_at` DATETIME DEFAULT NULL,
    `scopes_json` TEXT DEFAULT NULL,
    `config_json` TEXT DEFAULT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'disconnected',
    `last_synced_at` DATETIME DEFAULT NULL,
    `last_error_code` VARCHAR(100) DEFAULT NULL,
    `created_by` INT UNSIGNED DEFAULT NULL,
    `updated_by` INT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_search_insights_provider` (`provider`),
    KEY `idx_search_insights_status` (`status`, `last_synced_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_metrics` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `provider` VARCHAR(30) NOT NULL,
    `property_key` VARCHAR(191) NOT NULL,
    `metric_date` DATE NOT NULL,
    `dimension` VARCHAR(40) NOT NULL,
    `dimension_key` TEXT NOT NULL,
    `dimension_hash` CHAR(64) NOT NULL,
    `clicks` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `impressions` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `ctr` DECIMAL(12,8) NOT NULL DEFAULT 0,
    `avg_position` DECIMAL(12,4) NOT NULL DEFAULT 0,
    `users` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `sessions` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `pageviews` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `conversions` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `citations` DECIMAL(20,4) NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_search_metric` (`provider`, `property_key`, `metric_date`, `dimension`, `dimension_hash`),
    KEY `idx_search_metric_date` (`provider`, `metric_date`, `dimension`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_url_inspections` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(2048) NOT NULL,
    `url_hash` CHAR(64) NOT NULL,
    `verdict` VARCHAR(80) DEFAULT NULL,
    `coverage_state` VARCHAR(191) DEFAULT NULL,
    `robots_state` VARCHAR(80) DEFAULT NULL,
    `indexing_state` VARCHAR(80) DEFAULT NULL,
    `google_canonical` VARCHAR(2048) DEFAULT NULL,
    `user_canonical` VARCHAR(2048) DEFAULT NULL,
    `last_crawl_at` DATETIME DEFAULT NULL,
    `rich_results_json` TEXT DEFAULT NULL,
    `inspected_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_search_inspection_url` (`url_hash`),
    KEY `idx_search_inspection_verdict` (`verdict`, `inspected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_pagespeed` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `url` VARCHAR(2048) NOT NULL,
    `url_hash` CHAR(64) NOT NULL,
    `strategy` VARCHAR(20) NOT NULL,
    `performance_score` SMALLINT UNSIGNED DEFAULT NULL,
    `accessibility_score` SMALLINT UNSIGNED DEFAULT NULL,
    `best_practices_score` SMALLINT UNSIGNED DEFAULT NULL,
    `seo_score` SMALLINT UNSIGNED DEFAULT NULL,
    `lcp_ms` DECIMAL(14,2) DEFAULT NULL,
    `cls` DECIMAL(12,6) DEFAULT NULL,
    `inp_ms` DECIMAL(14,2) DEFAULT NULL,
    `fcp_ms` DECIMAL(14,2) DEFAULT NULL,
    `tbt_ms` DECIMAL(14,2) DEFAULT NULL,
    `checked_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_search_pagespeed` (`url_hash`, `strategy`),
    KEY `idx_search_pagespeed_checked` (`checked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_geo` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `engine` VARCHAR(40) NOT NULL,
    `observed_at` DATETIME NOT NULL,
    `prompt` TEXT NOT NULL,
    `prompt_hash` CHAR(64) NOT NULL,
    `cited_url` VARCHAR(2048) DEFAULT NULL,
    `cited_url_hash` CHAR(64) DEFAULT NULL,
    `citation_position` SMALLINT UNSIGNED DEFAULT NULL,
    `sentiment` VARCHAR(20) NOT NULL DEFAULT 'neutral',
    `answer_summary` TEXT DEFAULT NULL,
    `created_by` INT UNSIGNED DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    KEY `idx_search_geo_engine_date` (`engine`, `observed_at`),
    KEY `idx_search_geo_prompt` (`prompt_hash`, `observed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `{{prefix}}plugin_search_insights_merchant_issues` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `account_id` VARCHAR(20) NOT NULL,
    `scope` VARCHAR(20) NOT NULL,
    `subject_key` VARCHAR(191) NOT NULL,
    `issue_code` VARCHAR(191) NOT NULL,
    `issue_hash` CHAR(64) NOT NULL,
    `title` VARCHAR(500) NOT NULL,
    `detail` TEXT DEFAULT NULL,
    `severity` VARCHAR(30) NOT NULL,
    `resolution` VARCHAR(100) DEFAULT NULL,
    `attribute_name` VARCHAR(191) DEFAULT NULL,
    `reporting_context` VARCHAR(500) DEFAULT NULL,
    `countries_json` TEXT DEFAULT NULL,
    `documentation_url` VARCHAR(2048) DEFAULT NULL,
    `observed_at` DATETIME NOT NULL,
    `last_seen_at` DATETIME NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_search_merchant_issue` (`issue_hash`),
    KEY `idx_search_merchant_scope` (`account_id`, `scope`, `severity`),
    KEY `idx_search_merchant_seen` (`last_seen_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
